name: Upload to S3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Configure git email
        run: ls -al

      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: kiosk-rpi-files
          source_dir: 'prepare-kiosk.sh'